spring : 
  #数据库配置 
  datasource :      
    url : jdbc:mysql://94.191.18.52:3306/yandesign?useUnicode=true&characterEncoding=utf8
    username : root
    password : 147qwe
    driver-class-name : com.mysql.jdbc.Driver  
  application:
    name: yandesign
  mvc: 
      throw-exception-if-no-handler-found : true
  resources : 
      add-mappings : false
  #下载大小   
  servlet:
    multipart:
     max-file-size: 500MB
     max-request-size: 500MB 
     
     
#mybatis配置
mybatis-plus: 
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  typeAliasesPackage :  com.main.page.entity.*
  global-config:
      # 数据库相关配置
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: 3
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: 1
      refresh-mapper: true
      
logging:
  level:
     com.main.page.mapper : debug
  